# Generated by Django 3.1.6 on 2021-02-27 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210227_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.continent'),
        ),
    ]
