# Generated by Django 3.1.6 on 2021-02-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210225_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(default='images/country-flag/hacker.jpg', upload_to='images/country-flag'),
        ),
    ]
